name: Manual Operations Workflow

# This workflow will only run when manually triggered using the GitHub UI or API
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production
      build_type:
        description: 'Type of build to perform'
        required: true
        default: 'default'
        type: choice
        options:
          - default
          - release
          - debug

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Go version from go.mod
        id: go-version
        run: |
          GO_VERSION=$(grep -E '^go [0-9]+\.[0-9]+(\.[0-9]+)?' go.mod | awk '{print $2}')
          echo "GO_VERSION=$GO_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go-version.outputs.GO_VERSION }}
          cache: true

      - name: Display build information
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Build Type: ${{ github.event.inputs.build_type }}"
          echo "Go Version: ${{ steps.go-version.outputs.GO_VERSION }}"

      - name: Verify module configuration
        run: go mod verify

      - name: Build application
        run: |
          BUILD_FLAGS=""
          if [ "${{ github.event.inputs.build_type }}" = "release" ]; then
            BUILD_FLAGS="-ldflags '-s -w'"
          elif [ "${{ github.event.inputs.build_type }}" = "debug" ]; then
            BUILD_FLAGS="-gcflags 'all=-N -l'"
          fi
          
          eval "go build $BUILD_FLAGS -o k8s-rules-viewer ./cmd/main.go"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: k8s-rules-viewer-${{ github.event.inputs.environment }}-${{ github.event.inputs.build_type }}
          path: k8s-rules-viewer
          retention-days: 7
